version: '3'
services:
  mes-courses-app:
    image: aranuud/mes-courses:api
    networks:
      - mes-courses-network
    ports:
      - "3010:80"
      - "3011:443"

  mes-courses-api:
    image: aranuud/mes-courses:api
    depends_on:
      - mes-courses-db
    environment:
      - spring.application.name=
      - server.servlet.context-path=
      - spring.datasource.url=
      - spring.datasource.username=
      - spring.datasource.password=
      - spring.datasource.driver-class-name=
      - spring.jpa.properties.hibernate.default_schema=
      - spring.jpa.hibernate.ddl-auto=
      - spring.jpa.show-sql=
      - spring.jpa.properties.hibernate.format_sql=
      - spring.jpa.open-in-view=
      - server.port=80
      - server.address=0.0.0.0
      - server.error.include-stacktrace=never
      - allowed.origin=
      - security.jwt.secret-key=
      - security.jwt.expiration-time=
      - spring.servlet.multipart.max-file-size=
      - spring.servlet.multipart.max-request-size=
      - spring.flyway.enabled=true
      - spring.flyway.locations=classpath:db/migration
    networks:
      - mes-courses-network
    ports:
      - "4010:80"
      - "4011:443"

  mes-courses-db:
    image: postgres
    restart: always
    networks:
      - mes-courses-network
    environment:
      - POSTGRES_DB=mes-courses-dev
      - POSTGRES_USER=mes-courses-dev
      - POSTGRES_PASSWORD=mes-courses-dev
    ports:
      - "5010:5432"
      - "5011:443"

volumes:
  postgres_data:

networks:
  mes-courses-network:
    driver: bridge